name: Update Formula

on:
  push:
   tags:
     - '*'

jobs:
  release:
    strategy:
      matrix:
        os: [macos-11]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Update Formula
      id: update_formula
      run: |
        VERSION=${GITHUB_REF/refs\/tags\//}
        URL="https://github.com/evandcoleman/Scipio/archive/refs/tags/$VERSION.tar.gz"
        TAP_REPO="evandcoleman/homebrew-tap"
        REPO_PATH=$(pwd)

        brew tap evandcoleman/tap https://$GITHUB_USER:$GITHUB_TOKEN@github.com/$TAP_REPO.git
        cd $(brew --repository $TAP_REPO)
        
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config --global user.name $GITHUB_ACTOR
        git checkout -b formula/scipio/$VERSION

        sed -E -i '' 's~^  url ".*"~  url "'$URL\"~ Formula/scipio.rb
        brew fetch Formula/scipio.rb || true
        SHA256=$(shasum --algorithm 256 $(brew --cache --build-from-source Formula/scipio.rb) | awk '{print $1}')
        sed -E -i '' 's/^  sha256 ".*"/  sha256 "'$SHA256\"/ Formula/scipio.rb
        
        git add Formula/scipio.rb
        git commit -m "scipio $VERSION"
        git push origin formula/scipio/$VERSION
      env:
        GITHUB_TOKEN: ${{ secrets.HOMEBREW_GITHUB_TOKEN }}
        GITHUB_USER: ${{ secrets.HOMEBREW_GITHUB_USER }}
    - name: Open Pull Request
      id: open_pull_request
      run: |
        VERSION=${GITHUB_REF/refs\/tags\//}
        cd /usr/local/Homebrew/Library/Taps/evandcoleman/homebrew-tap
        curl -u $GITHUB_USER:$GITHUB_TOKEN -d '{"title": "Update Scipio to '"$VERSION"'", "base": "main", "head": "formula/scipio/'"$VERSION"'"}' https://api.github.com/repos/evandcoleman/homebrew-tap/pulls
      env:
        GITHUB_TOKEN: ${{ secrets.HOMEBREW_GITHUB_TOKEN }}
        GITHUB_USER: ${{ secrets.HOMEBREW_GITHUB_USER }}