name: Update Formula

on:
  pull_request:
    types: [ labeled ]

jobs:
  release:
    runs-on: macos-11
    if: ${{ github.event.label.name == 'pr-formula' }}
    steps:
    - uses: actions/checkout@v2
    - name: Update Formula
      id: update_formula
      run: |
        BRANCH=${GITHUB_HEAD_REF/refs\/heads\//}
        VERSION=${BRANCH#"$BRANCH_PREFIX"}
        URL="https://github.com/evandcoleman/Scipio/archive/refs/tags/$VERSION.tar.gz"
        TAP_REPO="evandcoleman/homebrew-tap"
        REPO_PATH=$(pwd)

        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config --global user.name $GITHUB_ACTOR

        git tag $VERSION
        git push origin $VERSION

        brew tap evandcoleman/tap https://$GITHUB_USER:$GITHUB_TOKEN@github.com/$TAP_REPO.git
        cd $(brew --repository $TAP_REPO)

        git checkout -b formula/scipio/$VERSION

        sed -E -i '' 's~^  url ".*"~  url "'$URL\"~ Formula/scipio.rb
        brew fetch Formula/scipio.rb || true
        SHA256=$(shasum --algorithm 256 $(brew --cache --build-from-source Formula/scipio.rb) | awk '{print $1}')
        sed -E -i '' 's/^  sha256 ".*"/  sha256 "'$SHA256\"/ Formula/scipio.rb
        
        git add Formula/scipio.rb
        git commit -m "scipio $VERSION"
        git push --force origin formula/scipio/$VERSION

        echo ::set-output name=version::$VERSION
      env:
        GITHUB_TOKEN: ${{ secrets.HOMEBREW_GITHUB_TOKEN }}
        GITHUB_USER: ${{ secrets.HOMEBREW_GITHUB_USER }}
        BRANCH_PREFIX: release/
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.update_formula.outputs.version }}
        release_name: Release ${{ steps.update_formula.outputs.version }}
        draft: false
        prerelease: false
    - name: Open Pull Request
      id: open_pull_request
      run: |
        cd /usr/local/Homebrew/Library/Taps/evandcoleman/homebrew-tap
        curl -u $GITHUB_USER:$GITHUB_TOKEN -d '{"title": "Update Scipio to '"$VERSION"'", "base": "main", "head": "formula/scipio/'"$VERSION"'"}' https://api.github.com/repos/evandcoleman/homebrew-tap/pulls
      env:
        GITHUB_TOKEN: ${{ secrets.HOMEBREW_GITHUB_TOKEN }}
        GITHUB_USER: ${{ secrets.HOMEBREW_GITHUB_USER }}
        VERSION: ${{ steps.update_formula.outputs.version }}
    - name: Merge Pull Request
      id: merge_pull_request
      run: |
        curl -u $GITHUB_USER:$GITHUB_TOKEN -X PUT https://api.github.com/repos/evandcoleman/Scipio/pulls/$PR_NUMBER/merge
      env:
        PR_NUMBER: ${{ github.event.number }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USER: ${{ github.actor }}
