name: Update Formula

on:
  push:
   branches:
     - 'release/*'

jobs:
  release:
    strategy:
      matrix:
        os: [macos-11]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Update Formula
      id: update_formula
      run: |
        BRANCH=${GITHUB_REF/refs\/heads\//}
        VERSION=${BRANCH#"$BRANCH_PREFIX"}
        URL="https://github.com/evandcoleman/Scipio/archive/refs/tags/$VERSION.tar.gz"
        TAP_REPO="evandcoleman/homebrew-tap"
        REPO_PATH=$(pwd)

        brew tap evandcoleman/tap https://$GITHUB_USER:$GITHUB_TOKEN@github.com/$TAP_REPO.git
        cd $(brew --repository $TAP_REPO)
        
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config --global user.name $GITHUB_ACTOR

        if [ $(git tag -l "$VERSION") ]; then
          git fetch origin formula/scipio/$VERSION
          git checkout formula/scipio/$VERSION
        else
          git checkout -b formula/scipio/$VERSION
        fi

        sed -E -i '' 's~^  url ".*"~  url "'$URL\"~ Formula/scipio.rb
        brew fetch Formula/scipio.rb || true
        SHA256=$(shasum --algorithm 256 $(brew --cache --build-from-source Formula/scipio.rb) | awk '{print $1}')
        sed -E -i '' 's/^  sha256 ".*"/  sha256 "'$SHA256\"/ Formula/scipio.rb
        
        git add Formula/scipio.rb
        git commit -m "scipio $VERSION"
        git push origin formula/scipio/$VERSION

        if [ $(git tag -l "$VERSION") ]; then
          echo "Tag already exists."
        else
          git tag $VERSION
          git push origin --tags
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.HOMEBREW_GITHUB_TOKEN }}
        GITHUB_USER: ${{ secrets.HOMEBREW_GITHUB_USER }}
        BRANCH_PREFIX: release/
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Open Pull Request
      id: open_pull_request
      run: |
        BRANCH=${GITHUB_REF/refs\/heads\//}
        VERSION=${BRANCH#"$BRANCH_PREFIX"}
        cd /usr/local/Homebrew/Library/Taps/evandcoleman/homebrew-tap
        curl -u $GITHUB_USER:$GITHUB_TOKEN -d '{"title": "Update Scipio to '"$VERSION"'", "base": "main", "head": "formula/scipio/'"$VERSION"'"}' https://api.github.com/repos/evandcoleman/homebrew-tap/pulls
      env:
        GITHUB_TOKEN: ${{ secrets.HOMEBREW_GITHUB_TOKEN }}
        GITHUB_USER: ${{ secrets.HOMEBREW_GITHUB_USER }}
        BRANCH_PREFIX: release/